# Getting necessary features for file:
# bot_cross_bu_dnc_stim_stage_detail

Here we will be isolating a couple features along with separating the data out by different rig company and eventually find the average of each feature per rig company

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import datetime

from dateutil.relativedelta import relativedelta

from datetime import date
import numpy as np
import seaborn as sns
import os
import missingno as msno

## Load in the file

In [2]:
path = "../SHARED/"
# notice order of files
files = [
    "clean_top_cross_bu_dnc_stim_stage_detail.xlsx",
    "clean_bot_cross_bu_dnc_stim_stage_detail.xlsx",
    "clean_gcbu_dnc_recompletions.xlsx",
    "clean_gcbu_dnc_stim_stage.xlsx",
    "clean_monthly_production.xlsx"
]

In [3]:
file = 1

df = pd.read_excel(path + files[file])
production = pd.read_excel(path + files[-1])

In [4]:
df

,#WELL_NAME,CURRENT_STATUS,UWI,UWI_SIDETRACK,JOB_CATEGORY,JOB_START_DATE,JOB_END_DATE,JOB_OP_CODE,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,...,FLUID_NAME,PUMPSONLINENO,USERNUM1,USERNUM3,DURPUMP,TOP_DEPTH_TVD,BOTTOM_DEPTH_TVD,PROPOSED,STIM_TREAT_REMARK,STG_REMARK
0,WELL - 2019000507,Producing,2019000507,0,COMPLETIONS,04/10/2017 00:00:00,04/26/2018 09:30:00,STIM,07/26/2017 06:00:00,08/18/2017 18:00:00,...,25# XL,NaN,NaN,NaN,NaN,11508.0,11504.0,0.0,STAGE 1 FRAC OPSSTART TIME: 02:31 HRS FI...,STAGE 1 FRAC OPSSTART TIME: 02:31 HRS FI...
1,WELL - 2019000477,Producing,2019000477,0,COMPLETIONS,12/06/2017 07:00:00,08/06/2018 18:00:00,STIM,01/20/2018 06:00:00,02/09/2018 09:00:00,...,25# GUAR BORATE,NaN,NaN,NaN,NaN,11598.0,11604.0,0.0,STAGE: 1 FRAC OPERATIONSSTART TIME: 20:33 HRS ...,STAGE: 1 FRAC OPERATIONSSTART TIME: 20:33 HRS ...
2,WELL - 2019000699,Producing,2019000699,0,COMPLETIONS,12/16/2018 06:00:00,10/12/2019 10:00:00,STIM,01/27/2019 06:00:00,02/03/2019 18:00:00,...,Slickwater,16.0,18.0,13.0,120.0,12872.0,12876.0,0.0,STAGE: 1 FRAC OPERATIONSSTART TIME: 0805 HRS ...,STAGE: 1 FRAC OPERATIONSSTART TIME: 0805 HRS ...
3,WELL - 2019000665,Producing,2019000665,0,COMPLETIONS,01/21/2018 10:00:00,10/09/2018 07:00:00,STIM,02/14/2018 08:00:00,02/23/2018 18:00:00,...,FRESH WATER,NaN,NaN,NaN,NaN,12991.0,13064.0,0.0,STAGE: 1 REFRAC OPERATIONSSTART TIME: 14:40 HR...,STAGE: 1 REFRAC OPERATIONSSTART TIME: 14:40 HR...
4,WELL - 2019000466,Producing,2019000466,0,COMPLETIONS,08/01/2017 06:00:00,NaN,STIM,09/08/2017 06:00:00,10/02/2017 06:00:00,...,Slick Water,NaN,NaN,NaN,NaN,10829.0,10826.0,0.0,STAGE 1 FRAC OPSSTART TIME: 13:35 HRS FI...,STAGE 1 FRAC OPSSTART TIME: 13:35 HRS FI...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17716,WELL - 2019000803,Suspended (I),2019000803,99,COMPLETIONS,07/19/2019 06:00:00,NaN,STIM,08/20/2019 06:00:00,09/04/2019 06:00:00,...,X-link gel,18.0,20.0,18.0,103.0,13130.0,13134.0,0.0,STAGE: 14 FRAC OPERATIONSSTART TIME: 18:59 HR...,STAGE: 14 FRAC OPERATIONSSTART TIME: 18:59 HR...
17717,WELL - 2019000078,Suspended (I),2019000078,0,COMPLETIONS,08/30/2018 09:00:00,05/03/2019 13:30:00,STIM,10/08/2018 06:00:00,11/06/2018 06:00:00,...,X-link gel,16.0,18.0,15.0,108.0,11574.0,11573.0,NaN,STAGE: 11 FRAC OPERATIONSSTART TIME: 01:59 HRS...,STAGE: 11 FRAC OPERATIONSSTART TIME: 01:59 HRS...
17718,WELL - 2019000803,Suspended (I),2019000803,99,COMPLETIONS,07/19/2019 06:00:00,NaN,STIM,08/20/2019 06:00:00,09/04/2019 06:00:00,...,X-link gel,18.0,20.0,17.0,152.0,13176.0,13176.0,0.0,STAGE: 4 FRAC OPERATIONSSTART TIME: 08:14 HRS...,STAGE: 4 FRAC OPERATIONSSTART TIME: 08:14 HRS...
17719,WELL - 2019000078,Suspended (I),2019000078,0,COMPLETIONS,08/30/2018 09:00:00,05/03/2019 13:30:00,STIM,10/08/2018 06:00:00,11/06/2018 06:00:00,...,X-link gel,17.0,18.0,16.0,110.0,11739.0,11735.0,0.0,STAGE: 36 FRAC OPERATIONS START TIME: 0147 HRS...,STAGE: 36 FRAC OPERATIONS START TIME: 0147 HRS...
17720,WELL - 2019000078,Suspended (I),2019000078,0,COMPLETIONS,08/30/2018 09:00:00,05/03/2019 13:30:00,STIM,10/08/2018 06:00:00,11/06/2018 06:00:00,...,X-link gel,16.0,19.0,15.0,116.0,11573.0,11566.0,NaN,STAGE: 9 FRAC OPERATIONSSTART TIME: 21:16 HRS ...,STAGE: 9 FRAC OPERATIONSSTART TIME: 21:16 HRS ...

In [5]:
df.columns

Index(['#WELL_NAME', 'CURRENT_STATUS', 'UWI', 'UWI_SIDETRACK', 'JOB_CATEGORY',
       'JOB_START_DATE', 'JOB_END_DATE', 'JOB_OP_CODE', 'RIG_ACCEPT_DATE',
       'RIG_RELEASE_DATE', 'RIG_TYPE', 'STIMTREAT_ID', 'JOB_STATUS',
       'LIKE_KIND', 'PROJECT_TYPE', 'PHASE_START_DATE', 'PHASE_END_DATE',
       'PHASE', 'RIG_ID', 'CONTRACTOR', 'REPORT_START_DATE_YEAR',
       'REPORT_START_DATE', 'REPORT_END_DATE', 'STIMULATION_TREAT_DATE',
       'STIMULATION_TREAT_TYPE', 'STIM_TREAT_COMPANY', 'STIM_TREAT_SUPERVISOR',
       'DIVERSION_COMPANY', 'DIVERSION_METHOD', 'DELIVERY_MODE',
       'FRAC_GRADIENT', 'BOTTOM_HOLE_PRESSURE_METHOD', 'BREAKDOWN_PRESSURE',
       'HYDROSTATIC_PRESSURE', 'TREAT_AVG_PRESSURE', 'TREAT_MAX_PRESSURE',
       'TREAT_MIN_PRESSURE', 'PROPPANT_DESIGNED', 'PROPPANT_IN_FORMATION',
       'PROPPANT_IN_WELLBORE', 'AVG_HYDRAULIC_POWER', 'MAX_PUMP_POWER',
       'MAX_PUMP_RATING', 'TREAT_AVG_RATE', 'TREAT_MAX_RATE', 'TREAT_MIN_RATE',
       'POST_INSTANT_SHUT_IN_PRESSURE', 'INITIAL_SHUT_IN_PRESSURE',
       'PRE_INSTANT_SHUT_IN_PRESSURE', 'STIMULATION_RESULT',
       'STIMULATION_RESULT_DETAIL', 'STG_NUMBER', 'STG_START_DATE',
       'STG_END_DATE', 'STG_TOP_DEPTH', 'STG_BOTTOM_DEPTH',
       'STG_ELEMENT_TOP_DEPTH', 'STG_ELEMENT_BOTTOM_DEPTH',
       'STG_INITIAL_PUMPING_PRESSURE', 'STG_FINAL_PUMPING_PRESSURE',
       'STG_BREAKDOWN_PRESSURE', 'STG_CLEAN_VOLUME_PUMPED',
       'STG_SLURRY_VOLUME_PUMPED', 'STG_VOLUME_RECOVERED', 'FLUID_NAME',
       'PUMPSONLINENO', 'USERNUM1', 'USERNUM3', 'DURPUMP', 'TOP_DEPTH_TVD',
       'BOTTOM_DEPTH_TVD', 'PROPOSED', 'STIM_TREAT_REMARK', 'STG_REMARK'],
      dtype='object')

In [6]:
# here due to the fact that my file did not contian the commented out files
# I just went ahead and replaced them with their STIM_INT counter parts.
# That could be an error to do, but for now I'll stick with it.

wanted_features = [
    "UWI",
    "CONTRACTOR",
    "RIG_ACCEPT_DATE",
    "RIG_RELEASE_DATE",
    "STG_START_DATE",           ## Missing
    "STG_END_DATE",             ## Missing
    "STG_SLURRY_VOLUME_PUMPED", ## Missing
    "PROPPANT_DESIGNED",        ## Missing
    "STG_TOP_DEPTH",
    "STG_BOTTOM_DEPTH",
  
]

In [7]:
# Remove those features that I wanted

working = df[wanted_features]

In [8]:
# Here because I did not want to work with an entry that did not have a rig
# contractor id, I just dropped it.

working = working.dropna(subset = ["CONTRACTOR"])

In [9]:
working = working.reset_index(drop = True)
working

,UWI,CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STG_START_DATE,STG_END_DATE,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,STG_TOP_DEPTH,STG_BOTTOM_DEPTH
0,2019000507,CONTRACTOR - 2019000008,07/26/2017 06:00:00,08/18/2017 18:00:00,07/27/2017 02:31:00,07/27/2017 04:31:00,3131,104000.0,18335.0,18400.0
1,2019000477,CONTRACTOR - 2019000027,01/20/2018 06:00:00,02/09/2018 09:00:00,01/23/2018 20:33:00,01/23/2018 21:22:00,2805,104000.0,17325.0,17390.0
2,2019000699,CONTRACTOR - 2019000027,01/27/2019 06:00:00,02/03/2019 18:00:00,01/28/2019 08:05:00,01/28/2019 10:05:00,4632,152125.0,17968.0,18041.0
3,2019000665,CONTRACTOR - 2019000030,02/14/2018 08:00:00,02/23/2018 18:00:00,02/19/2018 14:40:00,02/20/2018 00:19:00,24452,0.0,13063.0,18327.0
4,2019000466,CONTRACTOR - 2019000008,09/08/2017 06:00:00,10/02/2017 06:00:00,09/11/2017 13:35:00,09/11/2017 15:33:00,3768,104000.0,16246.0,16311.0
...,...,...,...,...,...,...,...,...,...,...
17716,2019000803,CONTRACTOR - 2019000008,08/20/2019 06:00:00,09/04/2019 06:00:00,08/25/2019 18:59:00,08/25/2019 20:42:00,7638,420000.0,20103.0,20247.0
17717,2019000078,CONTRACTOR - 2019000027,10/08/2018 06:00:00,11/06/2018 06:00:00,10/20/2018 01:59:00,10/20/2018 03:47:00,7500,420000.0,17502.0,17644.0
17718,2019000803,CONTRACTOR - 2019000008,08/20/2019 06:00:00,09/04/2019 06:00:00,08/23/2019 08:14:00,08/23/2019 10:46:00,7697,420000.0,21698.0,21841.0
17719,2019000078,CONTRACTOR - 2019000027,10/08/2018 06:00:00,11/06/2018 06:00:00,10/31/2018 01:47:00,10/31/2018 03:37:00,7375,420000.0,13577.0,13719.0
17720,2019000078,CONTRACTOR - 2019000027,10/08/2018 06:00:00,11/06/2018 06:00:00,10/18/2018 21:16:00,10/18/2018 23:12:00,7621,420000.0,17816.0,17958.0

In [10]:
# Converting all dates so that they will be easier to work with later.

dates = [
    "STG_START_DATE",
    "STG_END_DATE",
    "RIG_ACCEPT_DATE",
    "RIG_RELEASE_DATE"
]

for d in dates:
    working[d] = pd.to_datetime(working[d], dayfirst=True)

In [11]:
# Getting rid of the "fluff" that is infront of the rig contractor id
# so I'm re working the row so that only the id is there

for i in range(0, len(working)):
    working.loc[i, "CONTRACTOR"] = working.loc[i, "CONTRACTOR"].split(" ")[2]

In [12]:
working

,UWI,CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STG_START_DATE,STG_END_DATE,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,STG_TOP_DEPTH,STG_BOTTOM_DEPTH
0,2019000507,2019000008,2017-07-26 06:00:00,2017-08-18 18:00:00,2017-07-27 02:31:00,2017-07-27 04:31:00,3131,104000.0,18335.0,18400.0
1,2019000477,2019000027,2018-01-20 06:00:00,2018-09-02 09:00:00,2018-01-23 20:33:00,2018-01-23 21:22:00,2805,104000.0,17325.0,17390.0
2,2019000699,2019000027,2019-01-27 06:00:00,2019-03-02 18:00:00,2019-01-28 08:05:00,2019-01-28 10:05:00,4632,152125.0,17968.0,18041.0
3,2019000665,2019000030,2018-02-14 08:00:00,2018-02-23 18:00:00,2018-02-19 14:40:00,2018-02-20 00:19:00,24452,0.0,13063.0,18327.0
4,2019000466,2019000008,2017-08-09 06:00:00,2017-02-10 06:00:00,2017-11-09 13:35:00,2017-11-09 15:33:00,3768,104000.0,16246.0,16311.0
...,...,...,...,...,...,...,...,...,...,...
17716,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-25 18:59:00,2019-08-25 20:42:00,7638,420000.0,20103.0,20247.0
17717,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-20 01:59:00,2018-10-20 03:47:00,7500,420000.0,17502.0,17644.0
17718,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-23 08:14:00,2019-08-23 10:46:00,7697,420000.0,21698.0,21841.0
17719,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-31 01:47:00,2018-10-31 03:37:00,7375,420000.0,13577.0,13719.0
17720,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-18 21:16:00,2018-10-18 23:12:00,7621,420000.0,17816.0,17958.0

## Finding interpolated variables

In [13]:
inter_vars = [
    "Rig_Duration (days)",
    "Stg_Duration (hrs)",
    "Stage_Length (meters)",
    "Production (monthly)",
]

In [14]:
# Here we are simultaniously finding the rig duration and the stim_int duration
# So the process is that, if one of the dates is invalid (i.e. just missing)
# just write it as -1.

# If both dates are valid, but the release/end date is before the start date
# then put -1.

# Else, put in the correct duration in either days or in hours.

for i in range(0, len(working)):
    start_rig = working.loc[i, "RIG_ACCEPT_DATE"]
    end_rig = working.loc[i, "RIG_RELEASE_DATE"]
    if(pd.isnull(start_rig) or pd.isnull(end_rig)):
        working.loc[i, inter_vars[0]] = -1
    else:
        temp = (end_rig - start_rig).components.days
        if(temp < 0):
            working.loc[i, inter_vars[0]] = -1
        else:
            working.loc[i, inter_vars[0]] = temp
    
    
    start_stim = working.loc[i, "STG_START_DATE"]
    end_stim = working.loc[i, "STG_END_DATE"]
    if(pd.isnull(start_stim) or pd.isnull(end_stim)):
        working.loc[i, inter_vars[1]] = -1
    else:
        temp = (end_stim - start_stim).components.hours + 24 * (end_stim - start_stim).components.days
        if(temp < 0):
            working.loc[i, inter_vars[1]] = -1
        else:
            working.loc[i, inter_vars[1]] = temp

In [15]:
working

,UWI,CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STG_START_DATE,STG_END_DATE,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,STG_TOP_DEPTH,STG_BOTTOM_DEPTH,Rig_Duration (days),Stg_Duration (hrs)
0,2019000507,2019000008,2017-07-26 06:00:00,2017-08-18 18:00:00,2017-07-27 02:31:00,2017-07-27 04:31:00,3131,104000.0,18335.0,18400.0,23.0,2.0
1,2019000477,2019000027,2018-01-20 06:00:00,2018-09-02 09:00:00,2018-01-23 20:33:00,2018-01-23 21:22:00,2805,104000.0,17325.0,17390.0,225.0,0.0
2,2019000699,2019000027,2019-01-27 06:00:00,2019-03-02 18:00:00,2019-01-28 08:05:00,2019-01-28 10:05:00,4632,152125.0,17968.0,18041.0,34.0,2.0
3,2019000665,2019000030,2018-02-14 08:00:00,2018-02-23 18:00:00,2018-02-19 14:40:00,2018-02-20 00:19:00,24452,0.0,13063.0,18327.0,9.0,9.0
4,2019000466,2019000008,2017-08-09 06:00:00,2017-02-10 06:00:00,2017-11-09 13:35:00,2017-11-09 15:33:00,3768,104000.0,16246.0,16311.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17716,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-25 18:59:00,2019-08-25 20:42:00,7638,420000.0,20103.0,20247.0,-1.0,1.0
17717,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-20 01:59:00,2018-10-20 03:47:00,7500,420000.0,17502.0,17644.0,-1.0,1.0
17718,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-23 08:14:00,2019-08-23 10:46:00,7697,420000.0,21698.0,21841.0,-1.0,2.0
17719,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-31 01:47:00,2018-10-31 03:37:00,7375,420000.0,13577.0,13719.0,-1.0,1.0
17720,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-18 21:16:00,2018-10-18 23:12:00,7621,420000.0,17816.0,17958.0,-1.0,1.0

In [16]:
# Next find stage lenght for each entry
working[inter_vars[2]] = working["STG_BOTTOM_DEPTH"] - working["STG_TOP_DEPTH"]

In [17]:
working

,UWI,CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STG_START_DATE,STG_END_DATE,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,STG_TOP_DEPTH,STG_BOTTOM_DEPTH,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters)
0,2019000507,2019000008,2017-07-26 06:00:00,2017-08-18 18:00:00,2017-07-27 02:31:00,2017-07-27 04:31:00,3131,104000.0,18335.0,18400.0,23.0,2.0,65.0
1,2019000477,2019000027,2018-01-20 06:00:00,2018-09-02 09:00:00,2018-01-23 20:33:00,2018-01-23 21:22:00,2805,104000.0,17325.0,17390.0,225.0,0.0,65.0
2,2019000699,2019000027,2019-01-27 06:00:00,2019-03-02 18:00:00,2019-01-28 08:05:00,2019-01-28 10:05:00,4632,152125.0,17968.0,18041.0,34.0,2.0,73.0
3,2019000665,2019000030,2018-02-14 08:00:00,2018-02-23 18:00:00,2018-02-19 14:40:00,2018-02-20 00:19:00,24452,0.0,13063.0,18327.0,9.0,9.0,5264.0
4,2019000466,2019000008,2017-08-09 06:00:00,2017-02-10 06:00:00,2017-11-09 13:35:00,2017-11-09 15:33:00,3768,104000.0,16246.0,16311.0,-1.0,1.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17716,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-25 18:59:00,2019-08-25 20:42:00,7638,420000.0,20103.0,20247.0,-1.0,1.0,144.0
17717,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-20 01:59:00,2018-10-20 03:47:00,7500,420000.0,17502.0,17644.0,-1.0,1.0,142.0
17718,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-23 08:14:00,2019-08-23 10:46:00,7697,420000.0,21698.0,21841.0,-1.0,2.0,143.0
17719,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-31 01:47:00,2018-10-31 03:37:00,7375,420000.0,13577.0,13719.0,-1.0,1.0,142.0
17720,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-18 21:16:00,2018-10-18 23:12:00,7621,420000.0,17816.0,17958.0,-1.0,1.0,142.0

## Production stuff

In [18]:
# the way this method works is that, given a start and an end date
# the function will return a list of tuples that represent all the months and years
# that a given well operated for. The end month is included in the list.

# Example, if start date was 1/1/20 and end date was 3/1/20, the list that will
# return is: [(1,2020), (2,2020), (3,2020)]

# If an invalid date is given then it will return an empty list.
# If an invalid date range (end comes before start) an empty list will be returned.

def all_dates(start, end):
    to_return = []
    
    if(pd.isnull(start) or pd.isnull(end)):
        return to_return
    
    start_year = start.year
    start_month = start.month
    
    end_year = end.year
    end_month = end.month
    
    if(end_year < start_year):
        return to_return
    elif(end_year == start_year and end_month < start_month):
        return to_return
    
    
    if(end_month+1 == 12):
        end_month = 1
        end_year += 1
    if(end_month+1 == 13):
        end_month = 2
        end_year += 1
        
    while(start_year != end_year or start_month != end_month):
        to_return.append((start_month, start_year))
        start_month += 1
        if(start_month == 13):
            start_month = 1
            start_year += 1
    
    return to_return

In [19]:
# This method will return the total oil production of a given well along
# a list of dates.

# if no production is found, then -1 will be put.
def find_production(uwi, dates):
    total_prod = 0
    
    for date in dates:
        m = date[0]
        y = date[1]
        
        temp = production[(production["UWI"] == uwi) & 
                          (production["CYCLE_YEAR"] == y) & 
                          (production["CYCLE_MONTH"]== m)]
        
        temp = temp.reset_index(drop=True)
        
        if(len(temp) == 0):
            total_prod += 0
        else:
            total_prod += temp.loc[0, "LEASE_OIL_PROD_VOL"]
    
    if(total_prod == 0):
        return -1
    else:
        return total_prod

In [20]:
working["Oil Production (total)"] = np.nan

# Doing all this process to get the correct production for each entry
for i in range(0, len(working)):
    strt = working.loc[i, "RIG_ACCEPT_DATE"]
    end = working.loc[i, "RIG_RELEASE_DATE"]
    w_id = working.loc[i, "UWI"]
    rig_dur = working.loc[i, "Rig_Duration (days)"]
    
    if(rig_dur != -1):
        d = all_dates(strt, end)
        prod = find_production(w_id, d)
        working.loc[i, "Oil Production (total)"] = prod
    else:
        working.loc[i, "Oil Production (total)"] = -1

In [21]:
working

,UWI,CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STG_START_DATE,STG_END_DATE,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,STG_TOP_DEPTH,STG_BOTTOM_DEPTH,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters),Oil Production (total)
0,2019000507,2019000008,2017-07-26 06:00:00,2017-08-18 18:00:00,2017-07-27 02:31:00,2017-07-27 04:31:00,3131,104000.0,18335.0,18400.0,23.0,2.0,65.0,-1.0
1,2019000477,2019000027,2018-01-20 06:00:00,2018-09-02 09:00:00,2018-01-23 20:33:00,2018-01-23 21:22:00,2805,104000.0,17325.0,17390.0,225.0,0.0,65.0,605534.0
2,2019000699,2019000027,2019-01-27 06:00:00,2019-03-02 18:00:00,2019-01-28 08:05:00,2019-01-28 10:05:00,4632,152125.0,17968.0,18041.0,34.0,2.0,73.0,333.0
3,2019000665,2019000030,2018-02-14 08:00:00,2018-02-23 18:00:00,2018-02-19 14:40:00,2018-02-20 00:19:00,24452,0.0,13063.0,18327.0,9.0,9.0,5264.0,-1.0
4,2019000466,2019000008,2017-08-09 06:00:00,2017-02-10 06:00:00,2017-11-09 13:35:00,2017-11-09 15:33:00,3768,104000.0,16246.0,16311.0,-1.0,1.0,65.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17716,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-25 18:59:00,2019-08-25 20:42:00,7638,420000.0,20103.0,20247.0,-1.0,1.0,144.0,-1.0
17717,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-20 01:59:00,2018-10-20 03:47:00,7500,420000.0,17502.0,17644.0,-1.0,1.0,142.0,-1.0
17718,2019000803,2019000008,2019-08-20 06:00:00,2019-04-09 06:00:00,2019-08-23 08:14:00,2019-08-23 10:46:00,7697,420000.0,21698.0,21841.0,-1.0,2.0,143.0,-1.0
17719,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-31 01:47:00,2018-10-31 03:37:00,7375,420000.0,13577.0,13719.0,-1.0,1.0,142.0,-1.0
17720,2019000078,2019000027,2018-08-10 06:00:00,2018-06-11 06:00:00,2018-10-18 21:16:00,2018-10-18 23:12:00,7621,420000.0,17816.0,17958.0,-1.0,1.0,142.0,-1.0

In [22]:
# Saving off the working file

working.to_excel(path + "working_file_" + files[file], index = False)

In [23]:
# reduce the data frame to stuff we will use. So all the dates and the well
# ids are no longer needed.

final_features = [
    "CONTRACTOR",
    "STG_TOP_DEPTH",
    "STG_BOTTOM_DEPTH",
    "STG_SLURRY_VOLUME_PUMPED",
    "PROPPANT_DESIGNED",
    "Rig_Duration (days)",
    "Stg_Duration (hrs)",
    "Stage_Length (meters)",
]

In [24]:
final_df = working[final_features]

In [25]:
final_df

,CONTRACTOR,STG_TOP_DEPTH,STG_BOTTOM_DEPTH,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters)
0,2019000008,18335.0,18400.0,3131,104000.0,23.0,2.0,65.0
1,2019000027,17325.0,17390.0,2805,104000.0,225.0,0.0,65.0
2,2019000027,17968.0,18041.0,4632,152125.0,34.0,2.0,73.0
3,2019000030,13063.0,18327.0,24452,0.0,9.0,9.0,5264.0
4,2019000008,16246.0,16311.0,3768,104000.0,-1.0,1.0,65.0
...,...,...,...,...,...,...,...,...
17716,2019000008,20103.0,20247.0,7638,420000.0,-1.0,1.0,144.0
17717,2019000027,17502.0,17644.0,7500,420000.0,-1.0,1.0,142.0
17718,2019000008,21698.0,21841.0,7697,420000.0,-1.0,2.0,143.0
17719,2019000027,13577.0,13719.0,7375,420000.0,-1.0,1.0,142.0
17720,2019000027,17816.0,17958.0,7621,420000.0,-1.0,1.0,142.0

In [26]:
# This is just to find out how many unique rig contractors there are

unique_rigs = final_df["CONTRACTOR"].unique()
print(len(unique_rigs))
print(unique_rigs)

5
['2019000008' '2019000027' '2019000030' '2019000023' '2019000051']

In [27]:
all_rigs = []

for rig_id in unique_rigs:
    temp_rig = final_df[final_df["CONTRACTOR"] == rig_id].reset_index(drop = True)
    all_rigs.append(temp_rig)

In [28]:
# Here we will be standardizing every single entry so that we don't have
# to find a way to make the grades easier to calculate

# The formula that we'll be using is:

# standard value = abs(value - mean) / std
# except in the case that std is either null or 0, in those cases
# treat the std as 1 and continue with the formula

for rig in all_rigs:
    temp_describe = rig.describe()
    for feature in rig.columns.drop("CONTRACTOR"):
        mean = temp_describe.loc["mean", feature]
        std = temp_describe.loc["std", feature]
        if(pd.isnull(std) or std == 0):
            std = 1
        for i in range(0, len(rig)):
            rig.loc[i, feature] = abs(rig.loc[i, feature] - mean) / std

In [29]:
statistics = pd.DataFrame(
    columns = final_df.columns.drop("CONTRACTOR").insert(0, "RIG_ID").insert(1, "Stages Completed").drop("STG_TOP_DEPTH").drop("STG_BOTTOM_DEPTH")
)
statistics

Empty DataFrame
Columns: [RIG_ID, Stages Completed, STG_SLURRY_VOLUME_PUMPED, PROPPANT_DESIGNED, Rig_Duration (days), Stg_Duration (hrs), Stage_Length (meters)]
Index: []

In [30]:
# Add in the statistics for each rig into a final statistics dataframe
for rig in range(0, len(all_rigs)):
    temp_row = {
        'RIG_ID':                      "rig_%s" % (unique_rigs[rig]),
        'Stages Completed':            len(all_rigs[rig]),
        'STG_SLURRY_VOLUME_PUMPED':    all_rigs[rig].describe().loc["mean", "STG_SLURRY_VOLUME_PUMPED"],
        'PROPPANT_DESIGNED':           all_rigs[rig].describe().loc["mean", "PROPPANT_DESIGNED"],
        'Rig_Duration (days)':         all_rigs[rig].describe().loc["mean", "Rig_Duration (days)"],
        'Stg_Duration (hrs)':          all_rigs[rig].describe().loc["mean", "Stg_Duration (hrs)"],
        'Stage_Length (meters)':       all_rigs[rig].describe().loc["mean", "Stage_Length (meters)"],
    }
    statistics = statistics.append(temp_row, ignore_index = True)

In [31]:
statistics

,RIG_ID,Stages Completed,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters)
0,rig_2019000008,3455,0.624307,0.757750,0.791430,0.380349,0.335214
1,rig_2019000027,8790,0.741137,0.682595,0.806851,0.340516,0.468208
2,rig_2019000030,3825,0.849785,0.905209,0.786983,0.317384,0.242792
3,rig_2019000023,1191,0.693298,0.704638,0.899313,0.376871,0.676134
4,rig_2019000051,460,0.422722,0.230717,0.833932,0.354679,0.270677

In [32]:
statistics = statistics.set_index("RIG_ID")
statistics

,Stages Completed,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters)
RIG_ID,,,,,,
rig_2019000008,3455,0.624307,0.757750,0.791430,0.380349,0.335214
rig_2019000027,8790,0.741137,0.682595,0.806851,0.340516,0.468208
rig_2019000030,3825,0.849785,0.905209,0.786983,0.317384,0.242792
rig_2019000023,1191,0.693298,0.704638,0.899313,0.376871,0.676134
rig_2019000051,460,0.422722,0.230717,0.833932,0.354679,0.270677

In [33]:
# Calculating the grade

for rig in statistics.index:
    v_grade = 0.2 * statistics.loc[rig, "STG_SLURRY_VOLUME_PUMPED"]
    p_grade = 0.2 * statistics.loc[rig, "PROPPANT_DESIGNED"]
    r_grade = 0.1 * statistics.loc[rig, "Rig_Duration (days)"]
    s_grade = 0.35 * statistics.loc[rig, "Stg_Duration (hrs)"]
    l_grade = 0.15 * statistics.loc[rig, "Stage_Length (meters)"]
    statistics.loc[rig, "Grade"] = v_grade + p_grade + r_grade + s_grade + l_grade

In [34]:
statistics = statistics.sort_values(by = ["Grade"], ascending = False)
statistics

,Stages Completed,STG_SLURRY_VOLUME_PUMPED,PROPPANT_DESIGNED,Rig_Duration (days),Stg_Duration (hrs),Stage_Length (meters),Grade
RIG_ID,,,,,,,
rig_2019000023,1191,0.693298,0.704638,0.899313,0.376871,0.676134,0.602844
rig_2019000030,3825,0.849785,0.905209,0.786983,0.317384,0.242792,0.577201
rig_2019000027,8790,0.741137,0.682595,0.806851,0.340516,0.468208,0.554843
rig_2019000008,3455,0.624307,0.757750,0.791430,0.380349,0.335214,0.538959
rig_2019000051,460,0.422722,0.230717,0.833932,0.354679,0.270677,0.378820

In [35]:
statistics.to_excel(path + "grades_" + files[file])